### ISSUE TITLE
how can I get Maximum number of request per seconds

### ISSUE THREAD

**Issue by Ethan033100** [microsoft/azure-load-testing#54] opened 2022-02-21 09:36 UTC
I need to generate more than 20000 requests per seconds. I created a dummy example with APIM and azure function. 
I tried using the same JMeter script using 250 threads for 60 seconds.
I tried with 10 and 20 instances and I noticed that I was not able to achieve more than 2000 transactions per seconds. 
The most performant was the cluster with 10 instance, rather than the one with 20.

AB#1487102

**Comment by Ethan033100** [comment] 2022-02-22 02:23
I have a problem. My APIM is in southeastasia and azure load testing is in Australia.

I can see that the average number of users were 4264 and the p90 of the response time is 3.88 seconds.

I found an SSLException error, how can I solve it?

**Comment by Ethan033100** [comment] 2022-02-22 05:39
any updates?

**Comment by kaumishra** [comment] 2022-02-22 06:12
Hi Ethan, thanks for sharing. I am adding @abranj1219 from our dev team to help with this.

**Comment by Ethan033100** [comment] 2022-02-22 06:18
@abranj1219  Love, if you could help me tweak my configuration asap.

**Comment by abranj1219** [comment] 2022-02-22 06:58
@Ethan033100  This seems to be an interesting scenario.   We shall support you to generate that load. MALT can easily generate 20k rps. It would be great if you could share your APIM configuration. I believe you are already taking care of setting correct configuration on that part. But would be great to double check that and upgrading tier https://docs.microsoft.com/en-us/azure/api-management/upgrade-and-scale . Please  check and revert.

**Comment by Ethan033100** [comment] 2022-02-22 07:24
![JmeterConfig](https://user-images.githubusercontent.com/97595052/155082586-6d0a8c0d-3bc4-4867-a622-74dde9b5b2ac.jpg)
[APIMperformance.txt](https://github.com/microsoft/azure-load-testing/files/8114402/APIMperformance.txt)
these files may related. Thanks, if you can feel free to help check. @abranj1219

**Comment by Ethan033100** [comment] 2022-03-01 08:56
any updates?

**Comment by Ethan033100** [comment] 2022-03-11 03:57
I am using APIM Premium SKU

**Comment by Ethan033100** [comment] 2022-03-11 08:45
@abranj1219

**Comment by Ethan033100** [comment] 2022-03-17 09:33
Can I get any updates on this? Or other potential cause?

**Comment by harshan-b** [comment] 2022-03-21 05:57
@Ethan033100 It seems like the bottleneck is caused by APIM. Can you please check if there are any issues in Availability and Performance of APIM's Diagnose and Solve Problems tab? High round trip time in APIM can cause network timeouts (and SSL exceptions). It would be helpful if you could share more details about APIM and Azure function backend. Otherwise, I would suggest forwarding this issue to APIM

**Comment by abranj1219** [comment] 2022-03-22 18:13
@Ethan033100,   As @harshan-b  mentioned, We are able to achieve high scale if we remove APIM layer and directly load test premium function app. Could you check if you are able to achieve desired scale without APIM. This would confirm that it is related to APIM configurations and ALT can generate that much traffic indeed,

**Comment by abranj1219** [comment] 2022-04-01 07:40
@Ethan033100 , Could you confirm this if this was indeed related to APIM configuration? Would close this issue now. Please feel free to reopen in case you need further support

**Closed by abranj1219** 2022-04-01 07:40 UTC
Labels: help wanted
