### ISSUE TITLE
[BUG] Azure DevOps task not setting up ENV and Secrets

### ISSUE THREAD

**Issue by cathalmchale** [microsoft/azure-load-testing#126] opened 2022-11-24 13:24 UTC
**Describe the bug**
Azure DevOps task not setting up ENV and Secrets.

**To Reproduce**
1. Create an Azure DevOps pipeline with task to create/run an Azure Load Test.
2. Configure task with some ENV and Secret Json specified.
3. Run pipeline and observe that the created Azure Load Test has no ENV or Secrets configured.
4. Add some ENV and Secret values manually to the Load Test in the Azure Portal.
5. Re-run the pipeline and observe that the ENV and Secret values setup manually get erased.

**Expected behavior**
Required ENV and Secret values configured in the Azure Load Test by the CI/CD pipeline task.
Note: Do not get any error in the pipeline when creating the test / uploading the jmx for an already existing test. But when test runs with 100% errors and I click configure in the Azure Portal, I can see that the ENV and Secrets parameters are blank.

**Screenshots**
Have the Azure DevOps pipeline setup like below:

````
    - task: AzureLoadTest@1
      displayName: 'Run basic data verify test'
      inputs:
        azureSubscription: 'ARM via SP'
        loadTestConfigFile: '$(Build.SourcesDirectory)/devops/jmeter/HcapBasicDataVerifyConfig.yaml'
        resourceGroup: 'rg-perf-dev'
        loadTestResource: 'load-PerformanceTest-dev'
        secrets: |
          [
             {
              "name": "apimsupportsecret",
              "value": "https://vault-myorg-rsrc.vault.azure.net/secrets/LoadTest-MySupportUserSecret-DEV"
             }
          ]
        env: |
          [
             {
              "name": "apimroot",
              "value": "developer.myorg.com"
             },
             {
              "name": "apimsubscription",
              "value": "953efc736e7b46309711d013b57e4a97"
             },
             {
              "name": "apimsupportuser",
              "value": "MySupportUser"
             }
          ]
````

Above ENV / Secrets not configured when pipeline runs. If setup ENV / Secrets manually in Azure Portal, then run the pipeline again, it'll actually erase what you setup manually.

![image](https://user-images.githubusercontent.com/146731/203794203-dde52312-c4c6-4e7f-9987-3f493cba1c4c.png)

AB#1687200

**Comment by Nagarjuna-Vipparthi** [comment] 2022-11-24 16:48
@cathalmchale Can you please share the test run IDs for us to debug the issue? Thanks

**Comment by cathalmchale** [comment] 2022-11-24 17:09
- 1a1acdbd-821b-44e2-8176-9c6d69b7cbc3
- 098b14f7-ceb1-4e34-a9be-4a1631e131f7
- 442f1a11-fcc3-4c08-bf8d-4cd3cd58fd0b

Then I manually added back in ENV and Secrets to get Pass (should be only difference to 442f1a11-fcc3-4c08-bf8d-4cd3cd58fd0b above):

- 32c22b81-3811-4117-b681-e2841a3041f0

**Comment by cathalmchale** [comment] 2022-12-02 11:44
@Nagarjuna-Vipparthi could you find any root cause from the test runs for this issue?

**Comment by ninallam** [comment] 2022-12-15 10:34
@cathalmchale When you provide your env and secrets in the task directly, these are considered as runtime parameters and are available only for the test run. They are not persistent for the test. If you want the parameters to be persistent, you can define this in the YAML file directly as mentioned here https://learn.microsoft.com/azure/load-testing/reference-test-config-yaml. 
Closing this since it is not a bug. If you have any further questions, please reopen.

**Closed by ninallam** 2022-12-15 10:34 UTC
