### ISSUE TITLE
Run a test with files

### ISSUE THREAD

**Issue by adiazcan** [microsoft/azure-load-testing#55] opened 2022-02-21 14:58 UTC
I have a JMeter test plan that uploads a file to an endpoint using HTTP Post. I removed all the path reference from the file, as follow:

            <elementProp name="HTTPsampler.Files" elementType="HTTPFileArgs">
              <collectionProp name="HTTPFileArgs.files">
                <elementProp name="powerpoint.pptx" elementType="HTTPFileArg">
                  <stringProp name="File.path">powerpoint.pptx</stringProp>
                  <stringProp name="File.paramname">File</stringProp>
                  <stringProp name="File.mimetype">application/octet-stream</stringProp>
                </elementProp>
              </collectionProp>
            </elementProp>

When I ran the test, the processor didn't find the file and I had the following error: 

_Non HTTP response code: java.io.FileNotFoundException/Non HTTP response message: powerpoint.pptx (No such file or directory)_

When I downloaded the input files, the following files are on the artifacts zip:

![image](https://user-images.githubusercontent.com/6652046/154979488-47cd96de-644f-4d28-b1cc-2cda1c0fe7e6.png)

How can I reference the file on the test plan in order to use it on the tests? 

AB#1487169

**Comment by adiazcan** [comment] 2022-02-23 08:59
Hi @abranj1219, @ninallam 

Any help with attaching files for testing?

**Comment by Sachid26** [comment] 2022-02-25 06:11
Hi @adiazcan ... Thank you for reporting the issue. Could you please help us with the test plan if possible and the type of file you are trying to upload?

**Comment by adiazcan** [comment] 2022-03-09 13:48
Hello @Sachid26

Did you have time to review the files?

**Comment by Sachid26** [comment] 2022-03-09 19:17
Apologies for the delay. The zip seems to be empty when i try to extract the file.

**Comment by rithvikp1998** [comment] 2022-03-10 07:10
Hi @adiazcan,  I am unable to extract the files from the zip you gave, Windows just complains the file is invalid. I created a simple test plan which uploads a random file and it seems to be working well, both in our service and in my local machine. 

Are you able to run your test in your local machine? Can you please share the url to the test that failed in our service? 

These are the files I used to test:  
[FileUpload.zip](https://github.com/microsoft/azure-load-testing/files/8221096/FileUpload.zip)

**Comment by rithvikp1998** [comment] 2022-03-28 05:55
Hi @adiazcan Is the issue resolved? Or do you need any help with it?

**Comment by abranj1219** [comment] 2022-04-01 07:45
@adiazcan , Could you please confirm and get back. Closing this issue for now. Please feel free to repon in case you need any support

**Closed by abranj1219** 2022-04-01 07:45 UTC
Labels: help wanted

**Comment by adiazcan** [comment] 2022-04-01 12:10
Hi Team, sorry for not answering before, we had a lot of work testing our application using jmeter. 

We tested again and it didn't work but we don't know why. 

Our test work on local, running from jmeter gui, but when we upload the test plan and the attached file, the test failed on running on Azure with the not found file error.

**Comment by adiazcan** [comment] 2022-04-06 07:34
Hi @abranj1219 @rithvikp1998 

did you have time to see my latests messages?

**Comment by rithvikp1998** [comment] 2022-04-07 06:25
Hi @adiazcan I tried to reproduce the issue again and it looks like there is some race condition in JMeter/our service which is underreporting the number of samples. When I have 1 loop in my test plan, it is sometimes showing 0 samples (which we consider as a failed test) and sometimes showing 1 sample (which is considered a success). This is probably why I wasn't able to reproduce earlier. I am looking into what is causing this issue and I will get back to you when I find something
